### PR TITLE
Wiki update

### PR DESCRIPTION
**Pull request by mikebeaton**
I believe there is no mechanism for wiki pull requests, but wanted to offer the changes on https://github.com/mikebeaton/tianocore.github.io/wiki/How-to-Build-With-Stuart and https://github.com/mikebeaton/tianocore.github.io/wiki/How-to-Develop-With-Containers.

These are currently present as the following commits on https://github.com/mikebeaton/tianocore.github.io.wiki.git:

- **How-to-Build-With-Stuart.md**: Remove incorrect -p OvmfPkg
- **How-to-Build-With-Stuart.md**: Update default python command to python3
- **How-to-Build-With-Stuart.md**: Update venv instructions
  - ^^^ in respect of https://github.com/tianocore/edk2/pull/6255
- **How-to-Build-With-Stuart.md**: Provide brief rebuild BaseTools instructions where needed
- **How-to-Build-With-Stuart.md**: Add missing stuart_update step to OvmfPkg build instructions
- **How-to-Develop-With-Containers.md**: Add more detailed instructions on how to use VS Code containers with WSL 2

### CODE REVIEW

**Comment by mikebeaton** [comment]
cc @cfernald @makubacki

**Comment by makubacki** [comment]
> If I may, cc @cfernald @makubacki, as I believe authors of the two pages - tyvm

We used the mailing list in the past to share a patch, but I think pointing to a fork is fine.

I'm getting a 404 for <https://github.com/mikebeaton/tianocore.github.io.wiki.git> and I see the following at <https://github.com/mikebeaton/tianocore.github.io/wiki/Home/_history>:

image

If you're able to attach the patch files to a comment here, that would also work for me.

**Comment by mikebeaton** [comment]
The .git version I guess would just be for cloning.

This seems to work for actually showing the commits: https://github.com/mikebeaton/tianocore.github.io/wiki/_history

**Comment by mikebeaton** [comment]
Are the above links okay? I can send the patches instead, though (referring to the recent shift to GitHub for the main repo) it's definitely 'lower friction' for me (as a submitter) to prepare commits and then push them somewhere where they can be viewed, rather than the additional, rather non-trivial work of getting set up to send emailed patches correctly, plus the seeming higher likelihood that mail-based patches get discussed a little, then dropped. (I'm changing the topic slightly, as I know you're just asking for email-style patches attached here - and offering to take a proper look at them!)

I always wondered about the workflow of reviewers on dev lists which still use mailed-in patches... when I've needed to interact with such lists, then for all except the very smallest patches, I would just take and apply the patch, then view it in my favourite GUI diff viewer anyway - so basically it's turned from a commit into emails then back into a commit again, before it's in a form that I can at all easily work with! (I also never fully understood how on earth really large commits - 1000s of lines across 10s or hundreds of files for a new feature or large change - can be reviewed on email-based lists; though presumably it can be done, since I guess it has been. I guess the main idea is that developers should - somehow - always [avoid really large commits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#smaller-is-better-small-commits-small-pull-requests).) Anyway, that's a side track.... :-)

**Comment by makubacki** [comment]
> Are the above links okay? I can send the patches instead, though (referring to the recent shift to GitHub for the main repo) it's definitely 'lower friction' for me (as a submitter) to prepare commits and then push them somewhere where they can be viewed, rather than the additional, rather non-trivial work of getting set up to send emailed patches correctly, plus the seeming higher likelihood that mail-based patches get discussed a little, then dropped[.](https://www.reddit.com/r/emacs/comments/udjk8l/comment/i6hmtsg/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) (I'm changing the topic slightly, as I know you're just asking for email-style patches attached here - and offering to take a proper look at them!)
>

I completely agree with GitHub being the way to go versus patches over email. The wiki is one of the weak points in GitHub, unfortunately.

> I always wondered about the workflow of reviewers on dev lists which still use mailed-in patches... when I've needed to interact with such lists, then for all except the very smallest patches, I would just take and apply the patch, then view it in my favourite GUI git diff viewer anyway - so basically it's turned from a commit into emails then back into a commit again, before it's in a form that I can at all easily work with! (I also never fully understood how on earth really large commits - 1000s of lines across 10s or hundreds of files for a new feature or large change - can be reviewed on email-based lists; though presumably it can be done, since I guess it has been. I guess the main idea is that developers should - somehow - always [avoid really large commits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#smaller-is-better-small-commits-small-pull-requests).) Anyway, that's a side track.... :-)

Yeah, the mailing list-based process is error prone and tedious. Not only because of the transformation of patches (which can be impacted by each respective person's git settings) but all of the problems that come with corporate email policies impacting patch integrity. There are some philosophical reasons behind using the patches to avoid non-git tools, but I personally don't care about that and favor developer efficiency (which itself might be a controversial statement to others that have invested in efficient mailing list-based workflows).

---

- I think it would be helpful for [this change](https://github.com/mikebeaton/tianocore.github.io/wiki/_compare/381a1beff99cbc8588bad525a353e4ff74c148ee#diff-01e94c98e0b5f0603a0f10b1fde1a94826f05002de3f7d0d6e84c1d657733048R225) to refer to the exact commit [`517019a`](https://github.com/tianocore/edk2/commit/517019a55302b1222c152ee05226d55883050642) for reference.

Otherwise, it looks good. Let me know if you need any help pushing these commits to the wiki.

**Comment by mikebeaton** [comment]
I've updated the relevant change as requested: https://github.com/mikebeaton/tianocore.github.io/wiki/How-to-Build-With-Stuart/_compare/9356ffd7938e1a1b2571598aec6412cc07427b53...ba55ccbe58cd2ed7eeacfe7ca07e3496e2f74faf

> Let me know if you need any help pushing these commits to the wiki.

I don't have permissions to push to/edit the wiki, I did just double-check - so would need that, or your help - thanks!

**Comment by makubacki** [comment]
@mikebeaton, I pushed those commits - https://github.com/tianocore/tianocore.github.io/wiki/_history

**Comment by mikebeaton** [comment]
Looks good to me. Thank you.

**Pull request closed without merging**
