### PR TITLE
Archiving old Tianocore site, adding new site files

### PR DESCRIPTION
**Pull request by rporeilly**
Moved all old site files into _ARCHIVED and added new files into the root directory.

### CODE REVIEW

**Comment by jljusten** [comment]
I've been able to prototype changes to the site in this fork of the repo:
https://github.com/jljusten/tianocore
and preview at this url http://jljusten.github.io/tianocore

Maybe this will help to show demonstrate the new site?

Also, can't we migrate the new proposed layout in place and preserve as much as possible of the current site? (Rather than _ARCHIVED...)

**Comment by rporeilly** [comment]
Hi Jordan,

Unfortunately, given the very short timeframe of this project, and making it responsive, a "teardown" was the only efficient method.

And to confirm, are you asking me to fork the tianocaore repo for you and merge my updates there to preview?

**Comment by rporeilly** [comment]
Hi Jordan,

I’m looping Travis into our discussion on the redesign/rebuild of Tianocore, if you have any questions/need clarifications on this project's requirements, it would be best to pass them directly to him. Thanks!

Ryan O'Reilly
Senior Web Developer

thenewgroup
4540 SW Kelly Avenue
Portland, Oregon 97239
Office: 503-248-4505
Direct: 503-501-5093
www.thenewgroup.com<http://www.thenewgroup.com/>

_________________________________________________


Hi Jordan,

Unfortunately, given the very short timeframe of this project, and making it responsive, a "teardown" was the only efficient method.

And to confirm, are you asking me to fork the tianocaore repo for you and merge my updates there to preview?

**Comment by rporeilly** [comment]
Hi Jordan

Please let me know what questions you have and I can hopefully answer. I have added Laurie Jarlstrom and Steve Howard to this reply as they are our Intel contacts for the site rebuild.

Thanks

Travis Watkins
Production Director

thenewgroup
4540 SW Kelly Avenue
Portland, Oregon 97239
Office: 503-248-4505
Direct: 503-219-8487
www.thenewgroup.com<http://www.thenewgroup.com/>

**Comment by rporeilly** [comment]
Hi Jordan:

The tianocore.org facelift which TNG has been contracted to develop, has been authorized through all proper DMM channels and funded via the same.

I apologize for the fact that you have not been included in any of the planning and stakeholder meetings that have brought us to the point of going live with the new look and feel of tianocore.org (scheduled to have been live last Friday).

Your email is not very clear to my understanding. Are you suggesting TWO tianocore.org sites? (The “old” one and the “New” one?) The use of the word “fork” in terms of a web site seems to indicate to me that this is your intent.

The new tianocore.org look and feel (referenced as the “tianocore.org” facelift) has been modeled and reviewed using a “sandbox” server provided by TNG. All of the folks within PSI and EBP involved in the project have had opportunity to review and comment and make final decision to go live with what TNG has developed.

I have evangelized this facelift with the Intel customers and community members I work with (e.g. the IBVs). I am aware that there has been community discussion about it as well – taking us to this point, I believe.

I look forward to your response to help me better understand your positioning.

Thank you so much.

Best Regards,

Steven R. Howard  (Steve)
[cid:image001.gif@01CEA582.46D4DD50]
Intel SSG/STO/EBP
705 5th Ave S, Suite 500
Seattle, WA 98104
MS:UST1-4
(206) 701-8845 (Desk Direct)
(206) 434-0854 (Cell)

You have no choice but to operate in a world shaped by globalization and the information revolution. There are two options: adapt or die. - Andy Grove, 1995
-------
The opinions herein expressed are personal in nature and do not necessarily reflect those of Intel. There is no explicit endorsement of said opinions either by Intel or any of Intel's official representatives.

From: Travis Watkins [mailto:travis.watkins@thenewgroup.com]
Sent: Tuesday, June 30, 2015 12:44 PM
To: Ryan O'Reilly; tianocore/tianocore.github.io
Cc: Jarlstrom, Laurie; Howard, Steven R
Subject: RE: [tianocore.github.io] Archiving old Tianocore site, adding new site files (#1)

Hi Jordan

Please let me know what questions you have and I can hopefully answer. I have added Laurie Jarlstrom and Steve Howard to this reply as they are our Intel contacts for the site rebuild.

Thanks

Travis Watkins
Production Director

thenewgroup
4540 SW Kelly Avenue
Portland, Oregon 97239
Office: 503-248-4505
Direct: 503-219-8487
www.thenewgroup.com<http://www.thenewgroup.com/>

**Comment by jljusten** [comment]
After some manual integration the changes have mostly been merged. See http://www.tianocore.org. Thanks!

**Pull request closed without merging**
